# -- !Ups

-- To ensure UUIDs are autogenerated
create extension if not exists "uuid-ossp";

-- Constraint tables
create table metric_categories (
    name varchar not null constraint pk_metric_categories primary key,
    description varchar not null
);

insert into metric_categories (name, description) values ('StepData', 'Relating to step count data');

create table milestones (
    name varchar not null constraint pk_milestones primary key,
    milestone_category varchar not null constraint fk_milestones references categories,
    description varchar not null
);

insert into milestones (name, milestone_category, description)
values ('TenThousandSteps', 'StepData', 'When a user amasses 10,000 steps in their lifetime');
insert into milestones (name, milestone_category, description)
values ('FiftyThousandSteps', 'StepData', 'When a user amasses 50,000 steps in their lifetime');
insert into milestones (name, milestone_category, description)
values ('HundredThousandSteps', 'StepData', 'When a user amasses 100,000 steps in their lifetime');
insert into milestones (name, milestone_category, description)
values ('TwoFiftyThousandSteps', 'StepData', 'When a user amasses 250,000 steps in their lifetime');
insert into milestones (name, milestone_category, description)
values ('FiveHundredThousandSteps', 'StepData', 'When a user amasses 500,000 steps in their lifetime');
insert into milestones (name, milestone_category, description)
values ('OneMillionStepsSteps', 'StepData', 'When a user amasses 1,000,000 steps in their lifetime');
insert into milestones (name, milestone_category, description)
values ('TwoMillionStepsSteps', 'StepData', 'When a user amasses 2,000,000 steps in their lifetime');
insert into milestones (name, milestone_category, description)
values ('FiveMillionStepsSteps', 'StepData', 'When a user amasses 5,000,000 steps in their lifetime');
insert into milestones (name, milestone_category, description)
values ('TenMillionStepsSteps', 'StepData', 'When a user amasses 10,000,000 steps in their lifetime');

-- need id or no?
create table user_milestones (
    user_id uuid not null,
    milestone_name varchar not null constraint fk_milestone_name references milestones,
    milestone_category varchar not null constraint fk_milestone_category references categories,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    constraint unique_user_milestones unqiue (user_id, milestone_name)
);


-- Need tables to capture metrics and keep track
create table user_step_metrics (
    user_id uuid not null,
    metric_date varchar not null,
    steps_taken int not null,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    constraint unique_user_metric_per_day unqiue (user_id, metric_date)
)

# -- !Downs