apiVersion: apps/v1
kind: Deployment
metadata:
  name: awards-service
  namespace: awards
  labels:
    app: awards-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awards-service
  template:
    metadata:
      labels:
        app: awards-service
    spec:
      containers:
        # Sidecar container for cloudsql-proxy to connect to CloudSql database - recommended approach by Google for GKE
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          command:
            - /cloud_sql_proxy
            - -instances=fitcentive-dev-03:northamerica-northeast2:gke-dev-env-cloud-sql-instance:=tcp:5432
            - -credential_file=/secrets/cloudsql/credentials.json
          volumeMounts:
            - name: cloudsql-creds
              mountPath: /secrets/cloudsql
              readOnly: true
        - name: awards-service
          image: gcr.io/fitcentive-dev-03/awards:1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 500Mi
              cpu: "0.1"
            limits:
              memory: 1500Mi
              cpu: "0.5"
          ports:
            - name: http-port
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/awards/health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/awards/health
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 15
          envFrom:
            - secretRef:
                name: internal-service-secret
            - secretRef:
                name: awards-service-service-account-credentials
            - secretRef:
                name: awards-service-cloudsql-database-credentials
          env:
            - name: GCP_PROJECT_NAME
              value: "fitcentive-dev-03"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "5432"
            - name: RUNTIME_ENVIRONMENT
              value: "gke-dev-env"
            - name: JWT_ISSUER
              value: "https://auth.fitcentive.xyz"
            - name: KEYCLOAK_SERVER_URL
              value: "http://keycloak-service-http.keycloak/auth"
            - name: TOPIC_USER_ATTAINED_NEW_ACHIEVEMENT_MILESTONE
              value: "user-attained-new-achievement-milestone"
            - name: TOPIC_USER_STEP_DATA_UPDATED
              value: "user-step-data-updated"
            - name: SUBSCRIPTION_USER_STEP_DATA_UPDATED
              value: "user-step-data-updated"
      volumes:
        - name: cloudsql-creds
          secret:
            secretName: awards-service-cloudsql-instance-credentials