apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meetup-ingress
  namespace: meetup
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
spec:
  tls:
    - hosts:
        - api.fitcentive.xyz
      secretName: meetup-tls-certificate
  rules:
    - host: api.fitcentive.xyz
      http:
        paths:
          - path: /api/meetup
            pathType: Prefix
            backend:
              service:
                name: meetup-service
                port:
                  number: 9000
          - path: /api/internal/meetup
            pathType: Prefix
            backend:
              service:
                name: meetup-service
                port:
                  number: 9000