apiVersion: v1
kind: Service
metadata:
  name: meetup-service
  namespace: meetup
spec:
  selector:
    app: meetup-service
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 9000